import { Midi } from '@tonejs/midi'
import { INSTRUMENT_BY_ID } from './instruments'
import type { Composition } from './types'
import { MIDI_PERCUSSION_CHANNEL } from './types'

export function serializeMidi(composition: Composition): Uint8Array {
  const midi = new Midi()
  midi.name = composition.title
  midi.header.setTempo(composition.settings.tempo)
  midi.header.timeSignatures = [{ ticks: 0, timeSignature: [4, 4], measures: 0 }]
  midi.header.keySignatures = [{ ticks: 0, key: composition.settings.key, scale: composition.settings.scale === 'major' ? 'major' : 'minor' }]
  midi.header.meta = [
    { ticks: 0, type: 'text', text: `LoopSmith seed=${composition.settings.seed}; variation=${composition.settings.variation}` },
    { ticks: 0, type: 'copyrightNotice', text: 'Original procedural composition generated by LoopSmith' },
  ]
  midi.header.update()
  const secondsPerBeat = 60 / composition.settings.tempo
  composition.tracks.forEach((source) => {
    const track = midi.addTrack()
    track.name = source.name
    track.channel = source.role === 'drums' ? MIDI_PERCUSSION_CHANNEL : source.channel
    track.instrument.number = source.role === 'drums' ? 0 : INSTRUMENT_BY_ID[source.instrument].midiProgram
    track.addCC({ number: 7, time: 0, value: source.volume })
    track.addCC({ number: 10, time: 0, value: (source.pan + 1) / 2 })
    track.addCC({ number: 123, time: composition.durationSeconds, value: 0 })
    source.notes.forEach((note) => {
      track.addNote({
        midi: Math.max(0, Math.min(127, note.midi + source.octave * 12)),
        time: note.startBeats * secondsPerBeat,
        duration: note.durationBeats * secondsPerBeat,
        velocity: note.velocity,
      })
    })
    track.endOfTrackTicks = composition.totalBeats * midi.header.ppq
  })
  return midi.toArray()
}
